

def make_magic_method(name):
    def magic_method_to_pa_object(self, *args, **kwargs):
        from powerapp.core.pipeline.data_object.data_object import PowerAppObjectMethod

        return PowerAppObjectMethod(self, method=name)(*args, **kwargs)

    return magic_method_to_pa_object


class PossibleMagicMethodsToObject:
    __le__ = make_magic_method("__le__")
    __mod__ = make_magic_method("__mod__")
    __divmod__ = make_magic_method("__divmod__")
    __pos__ = make_magic_method("__pos__")
    __iadd__ = make_magic_method("__iadd__")
    __eq__ = make_magic_method("__eq__")
    __rrshift__ = make_magic_method("__rrshift__")
    __mul__ = make_magic_method("__mul__")
    __and__ = make_magic_method("__and__")
    __rfloordiv__ = make_magic_method("__rfloordiv__")
    __isub__ = make_magic_method("__isub__")
    __rand__ = make_magic_method("__rand__")
    __pow__ = make_magic_method("__pow__")
    __rxor__ = make_magic_method("__rxor__")
    __len__ = make_magic_method("__len__")
    __reduce_ex__ = make_magic_method("__reduce_ex__")
    __round__ = make_magic_method("__round__")
    __ixor__ = make_magic_method("__ixor__")
    __contains__ = make_magic_method("__contains__")
    __rmul__ = make_magic_method("__rmul__")
    __ior__ = make_magic_method("__ior__")
    __invert__ = make_magic_method("__invert__")
    __rshift__ = make_magic_method("__rshift__")
    __gt__ = make_magic_method("__gt__")
    __format__ = make_magic_method("__format__")
    __rdivmod__ = make_magic_method("__rdivmod__")
    __rtruediv__ = make_magic_method("__rtruediv__")
    __floor__ = make_magic_method("__floor__")
    __iand__ = make_magic_method("__iand__")
    __bool__ = make_magic_method("__bool__")
    __radd__ = make_magic_method("__radd__")
    __reversed__ = make_magic_method("__reversed__")
    __float__ = make_magic_method("__float__")
    __ror__ = make_magic_method("__ror__")
    __floordiv__ = make_magic_method("__floordiv__")
    __lshift__ = make_magic_method("__lshift__")
    __rlshift__ = make_magic_method("__rlshift__")
    __imul__ = make_magic_method("__imul__")
    __rpow__ = make_magic_method("__rpow__")
    __sub__ = make_magic_method("__sub__")
    __getitem__ = make_magic_method("__getitem__")
    __ne__ = make_magic_method("__ne__")
    __int__ = make_magic_method("__int__")
    __truediv__ = make_magic_method("__truediv__")
    __rmod__ = make_magic_method("__rmod__")
    __neg__ = make_magic_method("__neg__")
    __xor__ = make_magic_method("__xor__")
    __add__ = make_magic_method("__add__")
    __index__ = make_magic_method("__index__")
    __ceil__ = make_magic_method("__ceil__")
    __ge__ = make_magic_method("__ge__")
    __abs__ = make_magic_method("__abs__")
    __lt__ = make_magic_method("__lt__")
    __setitem__ = make_magic_method("__setitem__")
    __or__ = make_magic_method("__or__")
    __trunc__ = make_magic_method("__trunc__")
    __rsub__ = make_magic_method("__rsub__")
